USE [DGT]
GO

/****** Object:  Table [stg].[VHACDWA06CdwWorkInventoryequipmentinv6914engspace6928DSSDimDimLocationVha]    Script Date: 12/27/2021 11:11:22 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [stg].[VHACDWA06CdwWorkInventoryequipmentinv6914engspace6928DSSDimDimLocationVha](
	[station__no] [varchar](30) NOT NULL,
	[row_id] [numeric](28, 6) NULL,
	[entry_number] [varchar](8000) NULL,
	[entered_by] [varchar](8000) NULL,
	[enteredbyx] [varchar](8000) NULL,
	[date_entered] [datetime] NULL,
	[manufacturer] [varchar](8000) NULL,
	[manufacturerx] [varchar](8000) NULL,
	[parent_system] [varchar](8000) NULL,
	[parentsystemx] [varchar](8000) NULL,
	[mfgr_equipment_name] [varchar](8000) NULL,
	[model] [varchar](8000) NULL,
	[modelc] [varchar](8000) NULL,
	[serial_] [varchar](8000) NULL,
	[serial_c] [varchar](8000) NULL,
	[equipment_category] [varchar](8000) NULL,
	[equipmentcategoryx] [varchar](8000) NULL,
	[type_of_entry] [varchar](8000) NULL,
	[federal_supply_classification] [varchar](8000) NULL,
	[federalsupplyclassificationx] [varchar](8000) NULL,
	[lockout_required] [varchar](8000) NULL,
	[vendor_pointer] [varchar](8000) NULL,
	[vendorpointerx] [varchar](8000) NULL,
	[purchase_order_] [varchar](8000) NULL,
	[total_asset_value] [varchar](8000) NULL,
	[lease_cost] [varchar](8000) NULL,
	[acquisition_date] [datetime] NULL,
	[acquisition_source] [numeric](28, 6) NULL,
	[acquisitionsourcex] [varchar](8000) NULL,
	[warranty_exp_date] [datetime] NULL,
	[life_expectancy] [varchar](8000) NULL,
	[replacement_date] [datetime] NULL,
	[nxrn_] [varchar](8000) NULL,
	[category_stock_number] [varchar](8000) NULL,
	[categorystocknumberx] [varchar](8000) NULL,
	[cmr] [varchar](8000) NULL,
	[cmrx] [varchar](8000) NULL,
	[service_contract] [varchar](8000) NULL,
	[service_contract_cost] [varchar](8000) NULL,
	[use_status] [varchar](8000) NULL,
	[acquisition_method] [varchar](8000) NULL,
	[turnin_date] [datetime] NULL,
	[service_pointer] [varchar](8000) NULL,
	[servicepointerx] [varchar](8000) NULL,
	[disposition_date] [datetime] NULL,
	[physical_inventory_date] [datetime] NULL,
	[location] [varchar](8000) NULL,
	[locationx] [varchar](8000) NULL,
	[previous_location] [varchar](8000) NULL,
	[va_pm_number] [varchar](8000) NULL,
	[local_identifier] [varchar](8000) NULL,
	[jcaho] [varchar](8000) NULL,
	[bar_code_label_date] [datetime] NULL,
	[second_previous_location] [varchar](8000) NULL,
	[third_previous_location] [varchar](8000) NULL,
	[fourth_previous_location] [varchar](8000) NULL,
	[fifth_previous_location] [varchar](8000) NULL,
	[disposition_method] [varchar](8000) NULL,
	[dispositionmethodx] [varchar](8000) NULL,
	[original_asset_value] [numeric](28, 6) NULL,
	[disposition_value] [varchar](8000) NULL,
	[controlled_item] [varchar](8000) NULL,
	[investment_category] [varchar](8000) NULL,
	[fund_control_point] [varchar](8000) NULL,
	[cost_center] [varchar](8000) NULL,
	[costcenterx] [varchar](8000) NULL,
	[subaccount] [varchar](8000) NULL,
	[subaccountx] [varchar](8000) NULL,
	[standard_general_ledger] [varchar](8000) NULL,
	[standardgeneralledgerx] [varchar](8000) NULL,
	[yald_code] [varchar](8000) NULL,
	[commenpwp] [varchar](max) NULL,
	[replacing_entry_number] [numeric](28, 6) NULL,
	[replacingentrynumberx] [varchar](8000) NULL,
	[replacement_update_code] [varchar](8000) NULL,
	[condition_code] [varchar](8000) NULL,
	[station_number] [varchar](8000) NULL,
	[budget_object_code] [varchar](8000) NULL,
	[budgetobjectcodex] [varchar](8000) NULL,
	[fund] [varchar](8000) NULL,
	[fundx] [varchar](8000) NULL,
	[administrationoffice] [varchar](8000) NULL,
	[administrationofficex] [numeric](28, 6) NULL,
	[equity_account] [varchar](8000) NULL,
	[date_of_fap_conversion] [datetime] NULL,
	[reported_to_fap] [varchar](8000) NULL,
	[spexwp] [varchar](max) NULL,
	[y2k_category] [varchar](8000) NULL,
	[source_of_y2k_category] [varchar](8000) NULL,
	[estimated_y2k_compliance_date] [datetime] NULL,
	[actual_y2k_compliance_date] [datetime] NULL,
	[estimated_y2k_compliance_cost] [varchar](8000) NULL,
	[actual_y2k_compliance_cost] [numeric](28, 6) NULL,
	[y2k_technician] [numeric](28, 6) NULL,
	[y2ktechnicianx] [varchar](8000) NULL,
	[y2k_action] [varchar](8000) NULL,
	[y2k_estimated_replacement_date] [datetime] NULL,
	[y2k_assigned_shop] [numeric](28, 6) NULL,
	[y2kassignedshopx] [varchar](8000) NULL,
	[y2k_compliance_work_order_pointer] [varchar](8000) NULL,
	[y2kcomplianceworkorderpointerx] [varchar](8000) NULL,
	[y2k_compliance_work_order_text] [varchar](8000) NULL,
	[y2k_notes] [varchar](8000) NULL,
	[y2k_functional_classification] [varchar](8000) NULL,
	[y2k_utility_system] [varchar](8000) NULL,
	[y2kutilitysystemx] [varchar](8000) NULL,
	[nonspacefilelocation] [varchar](8000) NULL,
	[nonspacefilepersonid] [numeric](28, 6) NULL,
	[nonspacefileperson] [varchar](8000) NULL,
	[nonspacefiledatetime] [varchar](8000) NULL,
	[itremotelocation] [varchar](8000) NULL,
	[itcomments] [varchar](max) NULL,
	[remain_capitalized_set_by] [numeric](28, 6) NULL,
	[remaincapitalizedsetbyx] [varchar](8000) NULL,
	[thread__id] [numeric](18, 0) NULL,
	[visn] [int] NOT NULL,
	[sta3nname] [varchar](255) NULL,
	[sta6aname] [varchar](250) NULL,
	[sta5aname] [varchar](250) NULL,
	[room_number] [varchar](8000) NULL,
	[inverse_location] [varchar](8000) NULL,
	[building_number] [varchar](8000) NULL,
	[functionx] [varchar](8000) NULL,
	[servicex] [varchar](8000) NULL,
	[InsertDT] [datetime] NULL,
	[UserID] [varchar](100) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


